---
title: "All datasets"
---


The deportation data project posts five datasets: encounters, [arrests](docs-arrests.qmd),
detainers, detentions, and removals. They also have a list of offices scraped from the sub-office website of ICE.

In the `data/raw` folder, I've made an exact copy of the data that the
project posts. (Most recent in most cases.) There is also a copy that I
can use for hand-editing, with more descriptive data names. That's in
the `data/processed` folder, even though it's raw.

The project is pretty good about doing basic vetting of the datasets
when they arrive. For example, it immediately post the removals data
from July, when they found a serious flaw. They also post when each
dataset is usable as history.

The data originally is extracted from DHS's Enforcement Integrated Database, or EID, which is the back end to the department's ENFORCE application. It's supposed to hold details on the entire enforcement infrastructure, and is supposed to contain information from all of the enforcement agencies (I think).

The original data was downloaded from the Deportation Data Project, as of Oct. 13, 2025 (the date of this documentation). I'll update it when they get a new batch. I downloaded the original, not cleaned, data.

There are some things to remember about all of the datasets, and some
specific to individual ones.

### Other documentation

* [Deportation data project](https://deportationdata.org/docs/ice.html)'s original documentation for ICE data. In particular, the full "codebook" is the source for a lot of our understanding.

* There are some definitions that are still meaningful in the paper "[Piecing together the US Immigration Detention Puzzle One Night at a Time](https://journals.sagepub.com/doi/reader/10.1177/233150241500300402), Donald Kerwin and Daniela Alulema (Center for Migration Studies), Journal on Migration and Human Security, 2012.

## Common categories

There are a ton of variables that exist across all of the tables with the same meaning. Those are documented here. Columns specific to one table are defined in its documentation. The definitions lean heavily on the documentation provided by the Deportation Data Project.

::: todo

* [ ] Decide how to deal with crime codes so they're collapsed into meaningful categories that would be able to be used in a sentence.

:::

::: question

* [ ] Can we say that someone was only convicted of immigration offenses if that is the most serious crime? How can we characterize that?

:::

### Most serious crime categories

It's really unclear what is considered the "most serious" crime. In particular, it's unclear whether any immigration offense, such as illegal entry, is considered more serious than, say, a DUI.



1. TRAC, at some point, [got a list of offense codes from DHS](https://tracreports.org/immigration/reports/330/include/DocumentReleased_13-15734_Criminal_Offense_Level_Business_Rules.pdf) that lists the 'level' of each crime, as 1, 2, or 3. We can see there that illegal entry to the US is the lowest crime category. But it doesn't really help within the levels. (These were based on the old Morton memo, and haven't been in use for a long time, I don't think.)

2. The [American Immigration Council examined the "Most serious charge"](https://www.americanimmigrationcouncil.org/wp-content/uploads/2025/01/enforcement_overdrive_a_comprehensive_assessment_of_ices_criminal_alien_program_final.pdf) in the Criminal Alien Program that gives some detail on what they consider more and less serious.

  Also from the American Immigration Council:

::: blockquote

  “Aggravated felony” is a term of art used to describe a category of offenses carrying particularly harsh immigration consequences for noncitizens convicted of such crimes. Regardless of their immigration status, noncitizens who have been convicted of an “aggravated felony” are prohibited from receiving most forms of relief that would spare them from deportation, including asylum, and from being readmitted to the United States at any time in the future.

  Despite what the ominous-sounding name may suggest, an “aggravated felony” does not require the crime to be “aggravated” or a “felony” to qualify. Instead, an “aggravated felony” is simply an offense that Congress sees fit to label as such, and today includes many nonviolent and seemingly minor offenses.

  ...

  As initially enacted in 1988, the term “aggravated felony” referred only to murder, federal drug trafficking, and illicit trafficking of certain firearms and destructive devices. Congress has since expanded the definition of “aggravated felony” on numerous occasions, but has never removed a crime from the list. Today, the definition of “aggravated felony” covers more than thirty types of offenses, including simple battery, theft, filing a false tax return, and failing to appear in court.

:::

* [USCIS has a list of aggravated felonies](https://www.uscis.gov/policy-manual/volume-12-part-f-chapter-4) on its website, but I'm not sure how up to date it is.) (You can also be deported for crimes of "moral turpitude".)


4. The ICE custody worksheet suggests that the most serious crime conviction is based on the sentence, and nothing else: <https://www.ice.gov/doclib/detention-standards/2011/2-2.pdf>

## Case status and category codes

The case status and category codes contain remnants of the law as it existed before 1996, and have been constantly updated piecemeal. That makes them really difficult to understand. I've tried to combine and rename these codes into meaningful groups.

Although they mean different things, the case status and category tend to go together. In arrests, for example, they have the exact same number of missing values.

::: callout-warning

I still need to run these by an expert -- use with care.

:::

### Case status

At the highest level, refers to whether it is in ICE's purview. Anything that is ACTIVE is still on their books. Everything else is a reason that they're not. I've grouped ACTIVE with the missing values to create "Active case", and then grouped the 13 more detailed reasons into more general categories. The recodes are called `case_status_bln` in the tables.

New category | Original categories
-------------| ---------------------------------------------
Active case | ACTIVE
Left without arrest | 0-Withdrawal Permitted - I-275 Issued ; 3-Voluntary Departure Confirmed ; 9-VR Witnessed
Alien Enemies Act expulsion |  5-Title 50 Expulsion
Excluded / removed | 6-Deported/Removed - Deportability ; 8-Excluded/Removed - Inadmissibility;
No further action | 7-Died ;  A-Proceedings Terminated   ; E-Charging Document Canceled by ICE
Permanent residence granted | L-Legalization - Permanent Residence Granted ; Z-SAW - Permanent Residence Granted
Unknown | Missing values

### Case category

There are


## Data cleaning checks

#### Duplicates

True duplicates (every column exactly the same) are removed. But there are other types of duplication that are handled table-by-table. In some cases, they actually aren't duplicates -- they refer to more than one thing happening to a person or a case. In others, they're artifacts of a relational system and how they're handled depends on what the substantive question is. In still other cases, they **may** be duplicates, but we're not sure.

Generally:

* Duplicates across all fields, including missing values. Just save one -- it doesn't matter which.

* Dupes created by the relational nature of the data. For example, a person could be arrested twice, or they will show up over and over in the detention data. In each dataset, we can decide how to handle them for the purpose of local reporting. Using the same example in detention, for example, might mean that we want to create a snapshot for each detention location that has anyone who was ever in that area. For arrests, we may only want to keep the most recent OR we may want to create some summaries of arrests, and summaries of people, separately.


* Dupes that appear to be the same, but have different information. An example is an arrest record that differs in most cells, but has the same unique person ID and the same date and time as others. One answer is to look at the order that the file came in, and choose the one that appears to be the most recent (top or bottom of list in their original order), or see whether one of the values suggests it is a record that SHOULD be deleted (entered in error).


#### Missing unique identifiers

ICE is supposed to provide a scrambled unique identifier for each person but there are quite a few missing.


#### Dates and times

In each table, I checked to see if there is a meaningful time element to the date. If not, I converted the original column from date-time to just date. How this gets handled by others depends on the data processing software they use. If there is a meaningful time, then I added a column with the original name and the suffix `_part`


## Progress notes


::: question
- [ ] Is there any meaning to the original order of the file? This would affect what we do with duplicates.
- [ ] Are there any indicators of mistakes made in the data? (This might be a program code or something, or might be in the way they're ordred. In LIONS, for example, they're not allowed to just delete something, so they have to mark something for deletion instead when they make a mistake.)
:::
