---
author: Sarah Cohen
date: last-modified
title: Overview notes on Big Local Deportation Data project
subtitle: ""
# remaining customizations in _metadata.yml
---

::: confidential
NOT FOR PUBLICATION
:::

## Immigration data projects in the wild

### Deportation Data Project

The [Deportation data project](https://deportationdata.org/index.html)
is run by Graeme Blair of UCLA and David Hausman of Berkeley Law.
Together, they've sued DHS to obtain individual-level data from ICE and
CBP about encounters, arrests, detainers, detentions and removals. So
far it doesn't seem that they've gotten much from CBP, but they have
obtained the data from ICE. It gets updated irregularly, most recently
in September 2025 for data ending in July.

We spoke with Hausman in September, who told us a bit about the project
and about some of the uses for his data. In particular, he said that
news organizations had done a good job using local arrest data, for what
it's worth, but that the others take some decision-making and are a
little harder. In his view, the detention data would have the most use
for local reporters and is the most under-used.

Graeme is undertaking a project to make LIONS more accessible to
researchers and reporters -- I've had one interaction with him but
didn't hear back after I responded to his message.

The project is currently setting up "slicers" for their data, but is not
really trying to make it more accessible than that. Hausman said he
would welcome any help we can give in helping reporters use it -- they
are getting a lot of questions and requests for help, and they can't
handle it all. They need this help more than any technical help.

We talked with them about how Big Local could help fill that void.

They have [excellent documentation](https://deportationdata.org/docs/ice/codebook.html) of the terms used in deportation datasets - it's a great guide to what we know and what we don't about the data.

### Follow up from symposium of reporters

In June, Berkeley Journalism and a few other places [hosted a
symposium](https://docs.google.com/document/d/1TOFnulRtde2uO2xGK-ln0MYpgEZZzGDqsGoJSX6GeMU/edit?usp=sharing)
of reporters, experts, etc. to discuss immigration reporting. Our
contact there is Andrés Cediel, a documentarian with a lot of interest
in immigration issues. We spoke with him on Oct 10. They want to make
the data more transparent, and are focused on visualizations that could
be embedded. Others who are still involved include Mark Lima of CBS and
(I think) Lourdes Duarte from Chicago WGN.

Their inspiration was the COVID tracking project from the Atlantic.

His story ideas were pretty straightforward: US citizens getting caught
up in raids, looking at children , those without criminal records. They
are working with the Berkeley-based California News Fellowship (the
group that is funded by the Calif. government to fill holes in local
reporting.)

Ryan explained our model of working with a national outlet to do a story
that we can help get localized by partners that we've worked with
before, then have training materials, cleaned data, etc. to provide to
anyone once we know what we're doing. In a followup note, Andrès still
seemed focused on dashboard / visualizations, but Ryan clarified that.

He mentioned that LAT did a good job using the data after their
protests.

### Guardian US

Will Craft, who has done a lot of work with Big Local in the past, is
using the Deportation Data project pretty effectively, and is interested
in being our national partner. We're scheduled to talk with him next
week.

### Enforcement dashboard

The [immigration enforcement dashboard](https://austinkocher.substack.com/p/live-new-immigration-enforcement) was initialy released in September, but includes only arrest data for the time being. The project is led by [Austin Kocher](https://austinkocher.com/) an asst. research professor at Syracuse Journalism in the Office of Research and
Creative Technology.[^1]

[^1]: These are usually grant management divisions of schools, and there
    is nothing about it in the Newhouse School's website. So it's really
    unclear whether he works there or not. He's associated with Margaret
    Talev's group as well. Although he says he has a lot of research and
    media outlet work, it seems really out of date -- CSpan last year,
    and then nothing after 2022. He worked at TRAC while getting his PhD
    in geography.

There is a proof of concept at
<https://enforcementdashboard.com/ice-arrests/> for arrests, but it's
unclear if they are going beyond that. It's done by Kocher's company,
Relevant Research, which also has a site called
<https://detentionreports.com>. His numbers in detention can't be
separately sourced because he is using an imputation method to convert
year-to-date averages into daily populations by month.[^2]

[^2]: He starts with the [facilities
    report](https://www.ice.gov/detain/detention-management) published
    by ICE bi-monthly, then [calculates an
    "Interval"](https://relevant-research.com/assets/pdf/methodology_writeup.pdf)
    value. He takes a whole paper to say that he estimates the most
    recent two weeks' values by backing out the number of days. (ADP is
    calculated as total pop / total \# days for the fiscal year. Taking
    two time periods, can back out an ADP for the two weeks by taking
    ADP*Days period 1 - ADP* Days period 2 to get Days for Period 2, and
    then divide by the number of days.)

He has gotten historical numbers by week by going to the wayback
machine. ICE takes down the old links, but WAYBACK has them

On <https://austinkocher.substack.com/> , he has done some work
explaining what is in the data and what isn't.

The enforcement dashboard has some issues with functionality -- my guess
is that although the concept worked for aggregated stats that are in the
ICE detention data, it doesn't work for datasets with way more values in
it.

### Other possible sources

#### Interest groups

* Cato Institute, immigration project. It's unclear who we'd want to speak with - they have several people writing articles, including Scott Lincicome and David J. Bier. Bier published [at least one article](https://www.cato.org/blog/ice-arresting-1100-percent-more-noncriminals-streets-2017) referencing "nonpublic data" acquired by Cato that isn't anywhere else.

#### Reporters

* LA Times reporters who have been working with all of the data

* Tim Henderson, Stateline


## Datasets

The original data was downloaded from the Deportation Data Project, as of Oct. 13, 2025 (the date of this documentation). I'll update it when they get a new batch. I downloaded the original, not cleaned, data.

::: panel-tabset

## All datasets

The deportation data project posts five datasets: encounters, arrests,
detainers, detentions, and removals. They each have their own issues,
but some cross all of the datasets. They also have a list of detention
sites that can be used for mapping.

In the `data/raw` folder, I've made an exact copy of the data that the
project posts. (Most recent in most cases.) There is also a copy that I
can use for hand-editing, with more descriptive data names. That's in
the `data/processed` folder, even though it's raw.

The project is pretty good about doing basic vetting of the datasets
when they arrive. For example, it immediately post the removals data
from July, when they found a serious flaw. They also post when each
dataset is usable as history.

The data originally is extracted from DHS's Enforcement Integrated Database, or EID, which is the back end to the department's ENFORCE application. It's supposed to hold details on the entire enforcement infrastructure, and is supposed to contain information from all of the enforcement agencies (I think).

There are some things to remember about all of the datasets, and some
specific to individual ones.

Outstanding questions are shown in a callout under each section.

There are some definitions that are still meaningful in the paper "[Piecing together the US Immigration Detention Puzzle One Night at a Time](https://journals.sagepub.com/doi/reader/10.1177/233150241500300402), Donald Kerwin and Daniela Alulema (Center for Migration Studies), Journal on Migration and Human Security, 2012.

### Most serious crime categories

It's really unclear what they are using as the "most serious" crime category for the purpose of deportation. There are a couple of documents that can help:

1. TRAC, at some point, [got a list of offense codes from DHS](https://tracreports.org/immigration/reports/330/include/DocumentReleased_13-15734_Criminal_Offense_Level_Business_Rules.pdf) that lists the 'level' of each crime, as 1, 2, or 3. We can see there that illegal entry to the US is the lowest crime category. But it doesn't really help within the levels. (These were based on the old Morton memo, and haven't been in use for a long time, I don't think.)

2. The [American Immigration Council examined the "Most serious charge"]https://www.americanimmigrationcouncil.org/wp-content/uploads/2025/01/enforcement_overdrive_a_comprehensive_assessment_of_ices_criminal_alien_program_final.pdf) in the Criminal Alien Program that gives some detail on what they consider more and less serious.

Also from the American Immigration Council:

::: blockquote

“Aggravated felony” is a term of art used to describe a category of offenses carrying particularly harsh immigration consequences for noncitizens convicted of such crimes. Regardless of their immigration status, noncitizens who have been convicted of an “aggravated felony” are prohibited from receiving most forms of relief that would spare them from deportation, including asylum, and from being readmitted to the United States at any time in the future.

Despite what the ominous-sounding name may suggest, an “aggravated felony” does not require the crime to be “aggravated” or a “felony” to qualify. Instead, an “aggravated felony” is simply an offense that Congress sees fit to label as such, and today includes many nonviolent and seemingly minor offenses.

...

As initially enacted in 1988, the term “aggravated felony” referred only to murder, federal drug trafficking, and illicit trafficking of certain firearms and destructive devices. Congress has since expanded the definition of “aggravated felony” on numerous occasions, but has never removed a crime from the list. Today, the definition of “aggravated felony” covers more than thirty types of offenses, including simple battery, theft, filing a false tax return, and failing to appear in court.

:::

[USCIS has a list of aggravated felonies](https://www.uscis.gov/policy-manual/volume-12-part-f-chapter-4) on its website, but I'm not sure how up to date it is.

You can also be deported for crimes of "moral turpitude".

(The reason this matters is that it goes into the "most serious" crime category, I think.)

The ICE custody worksheet suggests that the most serious crime conviction is based on the sentence, and nothing else: https://www.ice.gov/doclib/detention-standards/2011/2-2.pdf



### Duplications

There are apparent duplications in each dataset. Some are not truly
dupes but are different events. For example, a single person arrested
can have a series of detention records as they are moved around by ICE.
Some are just mysterious. I'm handling different situations in different
ways, documented here.

### Missing unique identifiers

ICE is supposed to provide a scrambled unique identifier for each person
but there are quite a few missing.


### Famous cases

::: {.todo}
- [ ] Get a list of famous cases that should be followed through the system
  - Moving around detention
  - Arrest at courthouse
  - US citizens
  - Deaths
  - Children
:::

::: {.question}
-   [ ] Is the unique identifier the same over time?
-   [ ] What is the impact of this coming from ICE's Integrated Enforcement Database? Is any CBP data included? Should it be?

:::



