---
author: Sarah Cohen
date: last-modified
title: Untitled
subtitle: ""
format:
  scdefault-html: default  #/ requires _quarto.yml in root of project folder
execute:
  echo: false
  warning: false
  message: false
  error: true
  cache: false
  include: true
  eval: true

engine: knitr
---
::: confidential
NOT FOR PUBLICATION
:::

Make sure there is a file called _quarto.yml (it can be empty) at the project root.

This is an example document that you can use to remind yourself of some of the features of Quarto and to get some defaults that I am using for my analysis.

Generally, I don't use the TOC or margins, as I want to use as much of the page as possible. Change that with a [grid:](https://quarto.org/docs/output-formats/page-layout.html#grid-customization) statement in the yaml.

This creates a cache to speed things up, but it kind of messes up your folders. There's a lot there that gets saved.

::: callout-important
## Title!
Watch out for this!
:::

They are `callout-note`, `callout-tip`, `callout-caution`, `callout-warning`


## Overview

The following setup section should be customized. If you are working in a project in Positron, there is no need to use `here`, but it helps if you are working in RStudio.

These are the standard libraries I use a lot. For documents with Reactable tables, plots, etc, see the information on those sections. (Change "fenced" to "false" below to hide this code.)

```{r}
#| label: setup
#| message: false
#| echo: fenced
#| error: true

# assumes pacman has been installed already
pacman::p_load("tidyverse", "glue", "lubridate", "reactable", "reactablefmtr", "gt", "readxl", "here")

# put here::i_am () function here to make sure it finds the files relative to project.

```


## Reactable table example

Here, I'll put something to read in the custom theme, and then make a sample table using it. But for now, I'll leave this blank

This is an example of a pretty complicated Reactable table, but it works for the purpose of setting up a shell. The theme is in the utilities folder.





## ggplot defaults

Here, I'll add in some ggplot defaults, but for now I'll leave this blank.


